---
- name: 'Deploying App on Vsphere with Tanzu'
  hosts: 10.39.99.6
  user: root
  become: yes
  ignore_errors: yes
  
  tasks:
  - name: 'Creating pod'
    shell: "kubectl run pacman --image=harbor.lab39.sunfire.lab/test/test-s:${BUILD_NUMBER}"
    
  - name: 'Creating service'
    shell: "kubectl expose pod pacman --type=LoadBalancer --port=80 --target-port=80"
