---
- name: 'Deploying App on Vsphere with Tanzu'
  hosts: all
  user: root
  ignore_errors: yes
  
  tasks:
  - name: 'Creating namespace demo-ns'
    shell: 'kubectl create ns demo-ns'
      
  - name: 'Creating pod'
    shell: 'kubectl run --as=system:serviceaccount:default:psp pacmantags --image=harbor.lab39.sunfire.lab/test/test:tags -n demo-ns'
    
  - name: 'Creating service'
    shell: 'kubectl expose pod pacmantags --type=LoadBalancer --port=80 --target-port=80 -n demo-ns'
