---
- name: 'Deploying App on Vsphere with Tanzu'
  hosts: all
  user: root
  ignore_errors: yes
  
  tasks:
  - name: 'Creating namespace demo-ns'
    k8s:
      name: demo-ns
      api_version: v1
      kind: Namespace
      state: present
      
  - name: 'Creating pod pacmantags'
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: pacmantags
          namespace: demo-ns
          labels:
            app: gametags
        spec:
          containers:
          - name: pacmantags
            image: harbor.lab39.sunfire.lab/test/test-s:tags
    
  - name: 'Creating service'
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: pacman-service
          namespace: demo-ns
          labels:
            app: gametags
        spec:
          type: LoadBalancer
          selector:
            app: gametags
          ports:
          - protocol: TCP
            targetPort: 80
            name: pacmanport
            port: 80
