---
- name: 'Deploying App on Vsphere with Tanzu'
  hosts: all
  user: root
  ignore_errors: yes
  
  tasks:
  - name: 'Creating namespace demo-ns'
     k8s:
       name: demo-ns
       api_version: v1
       kind: Namespace
       state: present
      
  - name: 'Creating pod'
    shell: 'kubectl run pacmantags --image=10.39.100.5/test/test:tags -n demo-ns'
    
  - name: 'Creating service'
    shell: 'kubectl expose pod pacmantags --type=LoadBalancer --port=80 --target-port=80 -n demo-ns'
