---
- name: 'Deploying App on Vsphere with Tanzu'
  hosts: all
  ignore_errors: yes
  
  tasks:
  - name: 'Creating namespace'
    k8s:
      name: demo-ns
      api_version: v1
      kind: Namespace
      state: present
  - name: 'Creating pod'
    shell: "kubectl run pacman --image=harbor.lab39.sunfire.lab/test/test-s:${BUILD_NUMBER} -n demo-ns"
    
  - name: 'Creating service'
    shell: "kubectl expose pod pacman --type=LoadBalancer --port=80 --target-port=80 -n demo-ns"
